[project]
name = "ex1"
version = "0.1.0"
description = "poetry example install"
requires-python = ">=3.10"
dependencies = [
    "pandas==2.1.0",
    "numpy==1.26.4",
    "matplotlib==3.7.2",
    "requests==2.31.0",
]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pandas="2.1.0"
numpy="1.26.4"
matplotlib="3.7.2"
requests="2.31.0"
